name: cooki
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.0

  # Authentication
  firebase_auth: ^5.1.0

  # Beacon
  flutter_beacon: ^0.5.1

  # Navigation
  go_router: ^14.2.0

  # State
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  equatable: ^2.0.5

  # Permissions
  permission_handler: ^11.3.1
  app_settings: ^5.1.1

  # UI
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.6
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
