name: cooki
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.0

  # Authentication
  firebase_auth: ^5.1.0

  # Beacon
  flutter_beacon: ^0.5.1

  # Navigation
  go_router: ^14.2.0

  # State
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  equatable: ^2.0.5

  # Permissions
  permission_handler: ^11.3.1
  app_settings: ^5.1.1

  # UI
  fluttertoast: ^8.2.6
  flutter_markdown: ^0.7.3

  # Assets
  ionicons: ^0.2.2
  flutter_svg: ^2.0.10+1

  # API
  graphql_flutter: ^5.2.0-beta.7

  # Utils
  collection: ^1.18.0

  # Other
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/preferences/
    - assets/icons/chat/
    - assets/icons/map/
    - assets/imgs/

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
